### ISSUE TITLE
A question..

### ISSUE THREAD

**Issue by kuesttman** [Anon0511/gclone-docker#1]
A question..

Is it possible to use this docker-compose with gclone to perform the mount process? I would like to mount some units Using the SA accounts, and if by chance it reaches the rate limit, gclone will automatically switch to another SA account?

How would you use "gclone mount"? The JOB parameters do not have it.

**Comment by Anon0511** [comment]
Hey, thanks for asking. 
From what I know, gclone mount isn't any different to rclone mount. It does not automatically rotate Service Accounts on a mount. You would want to use rclone mount and use [SArotate](https://github.com/Visorask/sarotate) to inject the Service Account rotation via the --rc Port. But I think this image is too specific for a mount though, there should be a few rclone mount containers around anyway. I don't have one personally sadly, my mounts are still SystemD Services.
